routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/test', 'TestController@index');
Route::get('/statement-of-faith', 'HomeController@statementOfFaith')->name('statement-of-faith');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');
Route::get('/fellowships', 'HomeController@fellowships')->name('fellowships');
Route::post('/contacts', 'HomeController@email')->name('contacts.email');
Route::get('/salvation-prayer', 'HomeController@salvationPrayer')->name('salvation-prayer');
Route::get('/prophecies', 'HomeController@prophecies')->name('prophecies');
Route::get('/prophecies/fulfilled', 'HomeController@fulfilledProphecies')->name('fulfilled-prophecies');
Route::get('/stream/live', 'StreamController@live')->name('stream.live');

Route::resource('categories', 'CategoriesController')->only(['index', 'show']);
Route::resource('galleries', 'GalleriesController')->only(['index']);
Route::get('lernpunkte', 'NuggetsController@index')->name('nuggets.index');
Route::get('lernpunkte/{nugget}', 'NuggetsController@show')->name('nuggets.show');
Route::resource('slider-images', 'SlidersController')->only(['index']);

// Authentication Routes...
//Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
//Route::post('login', 'Auth\LoginController@login')->name('auth.login');
//Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');
//
//// Change Password Routes...
//Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
//Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
//
//// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'BackofficeController@index')->name('index');
    Route::get('/{any}', 'BackofficeController@index')->where('any', '.*');
});

app/Http/Controllers/BackofficeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackofficeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

        return view('backoffice.index', [
            'pageTitle' => 'Admin'
        ]);
    }
}

resources/views/backoffice/partials/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('admin.index')}}" aria-expanded="false">
                        <i class="mdi mdi-av-timer"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                @if($user->can('user_management_access'))
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                            <i class="mdi mdi-account-circle"></i>
                            <span class="hide-menu">@lang('site.user-management.title')</span>
                        </a>
                        <ul aria-expanded="false" class="collapse  first-level">
                            @if($user->can('user_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'users.index' }" class="sidebar-link">
                                    <i class="mdi mdi-account-network"></i>
                                    <span class="hide-menu">@lang('site.users.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('permission_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'permissions.index' }" class="sidebar-link">
                                    <i class="mdi mdi-lock"></i>
                                    <span class="hide-menu">@lang('site.permissions.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('role_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'roles.index' }" class="sidebar-link">
                                    <i class="mdi mdi-account-key"></i>
                                    <span class="hide-menu">@lang('site.roles.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('user_action_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'user_actions.index' }" class="sidebar-link">
                                    <i class="mdi mdi-account-check"></i>
                                    <span class="hide-menu">@lang('site.user-actions.title')</span>
                                </router-link>
                            </li>
                            @endif
                        </ul>
                    </li>
                @endif
                @if($user->can('content_management_access'))
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                            <i class="mdi mdi-file-document"></i>
                            <span class="hide-menu">@lang('site.content-management.title')</span>
                        </a>
                        <ul aria-expanded="false" class="collapse  first-level">
                            @if($user->can('user_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'categories.index' }" class="sidebar-link">
                                    <i class="mdi mdi-briefcase"></i>
                                    <span class="hide-menu">@lang('site.categories.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('video_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'videos.index' }" class="sidebar-link">
                                    <i class="mdi mdi-play-circle"></i>
                                    <span class="hide-menu">@lang('site.videos.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('gallery_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'galleries.index' }" class="sidebar-link">
                                    <i class="mdi mdi-image-album"></i>
                                    <span class="hide-menu">@lang('site.galleries.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('document_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'documents.index' }" class="sidebar-link">
                                    <i class="mdi mdi-file-pdf"></i>
                                    <span class="hide-menu">@lang('site.documents.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('slider_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'sliders.index' }" class="sidebar-link">
                                    <i class="mdi mdi-image-area"></i>
                                    <span class="hide-menu">@lang('site.slider.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('announcement_access'))
                            <li class="sidebar-item">
                                <router-link :to="{ name: 'announcements.index' }" class="sidebar-link">
                                    <i class="mdi mdi-calendar-clock"></i>
                                    <span class="hide-menu">@lang('site.announcements.title')</span>
                                </router-link>
                            </li>
                            @endif
                            @if($user->can('nugget_access'))
                                <li class="sidebar-item">
                                    <router-link :to="{ name: 'nuggets.index' }" class="sidebar-link">
                                        <i class="mdi mdi-image-album"></i>
                                        <span class="hide-menu">@lang('site.nuggets.title')</span>
                                    </router-link>
                                </li>
                            @endif
                        </ul>
                    </li>
                @endif
                <li class="sidebar-item">
                    <router-link :to="{ name: 'auth.change_password' }" class="sidebar-link waves-effect waves-dark sidebar-link">
                        <i class="mdi mdi-security"></i>
                        <span class="hide-menu">@lang('site.de_change_password')</span>
                    </router-link>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" onclick="event.preventDefault(); $('#logout').submit();" href="{{route('logout')}}" aria-expanded="false">
                        <i class="mdi mdi-power"></i>
                        <span class="hide-menu">@lang('site.de_logout')</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>