routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/test', 'TestController@index');
Route::get('/statement-of-faith', 'HomeController@statementOfFaith')->name('statement-of-faith');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');
Route::get('/fellowships', 'HomeController@fellowships')->name('fellowships');
Route::post('/contacts', 'HomeController@email')->name('contacts.email');
Route::get('/salvation-prayer', 'HomeController@salvationPrayer')->name('salvation-prayer');
Route::get('/prophecies', 'HomeController@prophecies')->name('prophecies');
Route::get('/prophecies/fulfilled', 'HomeController@fulfilledProphecies')->name('fulfilled-prophecies');
Route::get('/stream/live', 'StreamController@live')->name('stream.live');

Route::resource('categories', 'CategoriesController')->only(['index', 'show']);
Route::resource('galleries', 'GalleriesController')->only(['index']);
Route::get('lernpunkte', 'NuggetsController@index')->name('nuggets.index');
Route::get('lernpunkte/{nugget}', 'NuggetsController@show')->name('nuggets.show');
Route::resource('slider-images', 'SlidersController')->only(['index']);

// Authentication Routes...
//Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
//Route::post('login', 'Auth\LoginController@login')->name('auth.login');
//Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');
//
//// Change Password Routes...
//Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
//Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
//
//// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'BackofficeController@index')->name('index');
    Route::get('/{any}', 'BackofficeController@index')->where('any', '.*');
});

app/Nugget.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

/**
 * Class Nugget
 *
 * @package App
 * @property string $title
 * @property text $description
 * @property string $video_link
 * @property integer $order
 * @property string $show_on_front_page
 * @property string $active
 */
class Nugget extends Model implements HasMedia
{
    use SoftDeletes;
    use HasMediaTrait {
        HasMediaTrait::addMedia as parentAddMedia;
    }

    protected $fillable = ['title', 'description', 'video_link', 'order', 'show_on_front_page', 'slug', 'active'];
    protected $appends = ['images'];

    public static function boot()
    {
        parent::boot();

        Nugget::observe(new \App\Observers\UserActionsObserver);
    }

    public function getRouteKeyName()
    {
        if(!request()->expectsJson()) {
            return 'slug';
        }
        return 'id';
    }

    public static function storeValidation($request)
    {
        return [
            'title' => 'max:191|nullable',
            'description' => 'max:65535|nullable',
            'images' => 'nullable',
            'images.*' => 'file|image|nullable',
            'video_link' => 'max:191|nullable',
            'order' => 'integer|max:4294967295|nullable',
            'show_on_front_page' => 'in:1,0|max:191|nullable',
            'active' => 'in:1,0|max:191|required'
        ];
    }

    public static function updateValidation($request)
    {
        return [
            'title' => 'max:191|nullable',
            'description' => 'max:65535|nullable',
            'images' => 'sometimes',
//            'images.*' => 'file|image|nullable',
            'video_link' => 'max:191|nullable',
            'order' => 'integer|max:4294967295|nullable',
            'show_on_front_page' => 'in:1,0|max:191|nullable',
            'active' => 'in:1,0|max:191|required'
        ];
    }

    public function setSlugAttribute($title)
    {
        if ($title) {
            $slug = Str::slug($title);
            do {
                $this->attributes['slug'] = $slug;
                $exists = Nugget::where('slug', $slug)->first();
                $slug = $slug.'-'.Str::random(3);
            } while ($exists);
        }
    }

    public function addMedia($file)
    {
        return $this->parentAddMedia($file)
            ->usingFileName($file->hashName());
    }

    public function getImagesAttribute()
    {
        return $this->getMedia('images')->keyBy('id');
    }

    public function getUploadedImagesAttribute()
    {
        return $this->getMedia('images')->keyBy('id');
    }

    /**
     * @return string
     */
    public function getImagesLinkAttribute()
    {
        $images = $this->getMedia('images');
        if (!count($images)) {
            return null;
        }
        $html = [];
        foreach ($images as $file) {
            $html[] = '<a href="' . $file->getUrl() . '" target="_blank">' . '<img width="200" src="'.$file->getUrl().'"' . ' alt="'.$file->file_name.'" ></a>';
        }

        return implode('<br/>', $html);
    }

    /**
     * @return string
     */
    public function getLatestImagesAttribute()
    {
        return $this->getMedia('images')->take('10')->keyBy('id');
    }

    public function scopeFrontPageNuggets(Builder $builder) {
        return $builder->where('show_on_front_page', 1)->where('active', 1)->orderBy('id', 'desc');
    }

    public function scopeOtherNuggets(Builder $builder) {
        return $builder->where('active', 1)->orderBy('id', 'desc')->orderBy('order', 'asc');
    }

    public function scopeLatestNuggets(Builder $builder) {
        return $builder->latest()->where('active', 1)->orderBy('id', 'desc')->orderBy('order', 'asc')->first();
    }
}

app/Slider.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

/**
 * Class Slider
 *
 * @package App
 * @property string $title
 * @property text $description
 * @property string $image
 * @property string $video_link
 * @property string $active
 * @property integer $order
*/
class Slider extends Model implements HasMedia
{
    use SoftDeletes;

    use HasMediaTrait {
        HasMediaTrait::addMedia as parentAddMedia;
    }


    protected $fillable = ['title', 'description', 'video_link', 'active', 'order'];
    protected $appends = ['image', 'image_link'];
    protected $with = ['media'];


    public static function boot()
    {
        parent::boot();

        Slider::observe(new \App\Observers\UserActionsObserver);
    }

    public static function storeValidation($request)
    {
        return [
            'title' => 'max:191|nullable',
            'description' => 'max:65535|nullable',
            'image' => 'file|image|required',
            'video_link' => 'max:191|nullable',
            'active' => 'in:1,0|max:191|nullable',
            'order' => 'integer|max:4294967295|nullable'
        ];
    }

    public static function updateValidation($request)
    {
        return [
            'title' => 'max:191|nullable',
            'description' => 'max:65535|nullable',
            'image' => 'nullable',
            'video_link' => 'max:191|nullable',
            'active' => 'in:1,0|max:191|nullable',
            'order' => 'integer|max:4294967295|nullable'
        ];
    }

    public function addMedia($file)
    {
        return $this->parentAddMedia($file)
            ->usingFileName($file->hashName());
    }

    public function getImageAttribute()
    {
        return $this->getFirstMedia('image');
    }

    /**
     * @return string
     */
    public function getImageLinkAttribute()
    {
        $file = $this->getFirstMedia('image');
        if (! $file) {
            return null;
        }

        return '<a href="' . $file->getUrl() . '" target="_blank">' . '<img width="200" src="'.$file->getUrl().'"' . ' alt="'.$file->file_name.'" ></a>';
    }

    /**
     * @return string
     */
    public function getImageUrlAttribute()
    {
        $file = $this->getFirstMedia('image');
        if (! $file) {
            return null;
        }

        return $file->getUrl();
    }


}

resources/views/site/categories.blade.php
@extends('layouts.site')
@section('content')
    <section>
     <div class="container p-0">
         <div class="row">
             <div class="col-md-12">
                 <div class="card basic-page bg-white vh-100">
                     <div class="card-header">
                         <h4 class="card-title text-uppercase mb-0">{{__($pageTitle ?? $naturalPageTitle)}}</h4>
                     </div>
                     <div class="card-body p-3">
                        <div class="tags">
                            @foreach($categories as $category)
                                <a target="_blank" href="{{route('categories.show', $category)}}"><span>{{__($category->title)}}</span></a>
                            @endforeach
                        </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
    </section>
@endsection

resources/views/site/contacts.blade.php
@extends('layouts.site')
@section('content')
    <section>
        <div class="container p-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="card contacts-page basic-page">
                        <div class="card-header">
                            <h4 class="card-title text-uppercase mb-0">{{__($pageTitle)}}</h4>
                        </div>
                        <div class="card-body my-5">
                            @include('partials.flash-messages')
                            <div class="row justify-content-center">
                                <div class="col-md-7">
                                    <div class="card p-3 shadow">
                                    <div class="card-body">
                                        <form method="post" action="{{route('contacts.email')}}" class="mt-4">
                                            @csrf
                                            <div class="form-group">
                                                <input name="name" type="text"
                                                       class="form-control @error('name') is-invalid @enderror"
                                                       placeholder="{{__('Name')}}" value="{{ old('name') }}">
                                                @error('name')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group">
                                                <input name="email" type="email"
                                                       class="form-control @error('email') is-invalid @enderror"
                                                       placeholder="{{__('Email')}}" value="{{ old('email') }}">
                                                @error('email')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group">
                                                <input name="subject" type="text"
                                                       class="form-control @error('subject') is-invalid @enderror"
                                                       placeholder="{{__('Subject')}}" value="{{ old('subject') }}">
                                                @error('subject')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group">
                                                <textarea name="message" rows="7"
                                                          class="form-control @error('message') is-invalid @enderror"
                                                          placeholder="{{__('Message')}}">{{ old('message') }}</textarea>
                                                @error('message')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="mb-4">
                                                <div class="g-recaptcha"
                                                     data-sitekey="{{config('sys.settings.recaptcha.site')}}"></div>
                                                <div class="@error('g-recaptcha-response')is-invalid  @enderror">
                                                    @error('g-recaptcha-response')
                                                    <span class="invalid-feedback d-block">
                                                {{$message}}
                                            </span>
                                                    @endif
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-theme btn-lg btn-block"
                                                        type="submit">{{__('Send Message')}}</button>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/site/fellowships.blade.php
@extends('layouts.site')
@section('content')
    <section>
        <div class="container p-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="card basic-page">
                        <div class="card-header">
                            <h4 class="card-title text-uppercase mb-0">{{__($pageTitle)}}</h4>
                        </div>
                        <div class="card-body pb-3">
                            <div class="row">
                                @foreach($items as $item)
                                <div class="col-md-6 mb-4">
                                    <div class="callout callout-theme h-100">
                                        <h4 class="text-yellow">{{$item['name']}}</h4>
                                        <p>{!! $item['street'] !!}</p>
                                        <p>{!! $item['city_town_area'] !!}</p>
                                        <p>{!! $item['further_directions'] !!}</p>
                                        @isset($item['phone'])
                                        <p class="font-weight-bold text-orange">{{__("Phone")}}:&nbsp;{{$item['phone']}}</p>
                                        @endisset
                                        @isset($item['time'])
                                        <p class="font-weight-bold text-orange">{{$item['time']}}</p>
                                        @endisset
                                    </div>
                                </div>
                                @endforeach
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/site/galleries.blade.php
@extends('layouts.site')
@section('content')
    <section>
     <div class="container p-0">
         <div class="row">
             <div class="col-md-12">
                 <div class="card galleries basic-page border-0 bg-theme">
                     <div class="card-header">
                         <h4 class="card-title text-uppercase mb-0">{{__($pageTitle)}}</h4>
                     </div>
                     <div class="card-body">
                         <div class="row">
                             <div class="col-md-12">
                                 @foreach($galleries as $gallery)
                                     @if($gallery->images)
                                         <div class="item pb-3">
                                         <header><h4 class="text-yellow p-0">{{$gallery->title}}</h4></header>
                                         <p>{{$gallery->description}}</p>
                                         <div class="gallery-wrapper masonable-wrapper grid row no-gutters">
                                             <div class="col-md-3 grid-sizer"></div>
                                             @foreach($gallery->images as $image)
                                                 @php
                                                     $url = $image->getUrl();
                                                 @endphp
                                                 <a class="grid-item col-md-3" href="{{url($url)}}" data-fancybox="grid-gallery" data-caption="{{$gallery->title}}">
                                                     <div class="image-container">
                                                         <div class="overlay"></div>
                                                         <img class="shadow" src="{{url($url)}}">
                                                         <i class="fa fa-camera icon"></i>
                                                     </div>
                                                 </a>
                                             @endforeach
                                         </div>
                                         </div>
                                         <div class="be-border w-100 my-5"></div>
                                     @endif
                                 @endforeach
                             </div>
                             <div class="col-md-12 mt-4">
                                 {{$galleries->links()}}
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
    </section>
@endsection

resources/views/site/live.blade.php
@extends('layouts.site')
@section('content')
    <section>
        <div class="smart-marquee">
            <span>{{__($live_video->title ?? $naturalPageTitle)}}</span>
        </div>
        <div class="container h-100 p-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="card glorious-blue border-0">
                        <div class="card-header">
                            <div class="card-title text-uppercase mb-0">
                                <a href="{{route('home')}}" class="d-flex w-100 align-items-center justify-content-center text-yellow py-2">
                                    <img src="{{url('images/icons/logo.png')}}" width="40" height="40" alt="{{config('app.name')}}">
                                </a>
                            </div>
                        </div>
                        <div class="card-body p-0 glorious-blue">
                            <div class="item">
                                <div class="w-100 position-relative" style="padding-bottom: 56%">
                                    @if($live_video)
                                        <iframe class="position-absolute w-100 h-100" width="100%" src="{{$live_video->embed_link}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                    @else
                                        <div class="position-absolute w-100 h-100 d-flex align-items-center justify-content-center text-white">
                                            <div class="text-center">
                                                <i class="fa fa-video-slash error-emoji mb-3"></i>
                                                <h3 class="mb-4">Livestream is off</h3>
                                                <h5><a class="d-flex align-items-center justify-content-center" href="{{route('stream.live')}}"><i class="fa fa-undo text-yellow"></i><small class="text-yellow">&nbsp;refresh</small></a></h5>
                                            </div>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('styles')
    <style>

    </style>
@endpush

resources/views/site/nuggets-show.blade.php
@extends('layouts.site')
@section('content')
    <section>
        <div class="container p-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="card no-bg glorious-blue mb-4 basic-page">
                        <div class="card-header">
                            <h4 class="card-title text-uppercase mb-0"><a class="text-yellow" href="{{route('nuggets.index')}}">{{__('Nuggets')}}</a>&emsp;<i class="fa fa-angle-double-right"></i>&emsp;{{__($pageTitle ?? $naturalPageTitle)}}</h4>
                        </div>

                        <div class="card-body">
                            <div class="gallery-wrapper masonable-wrapper grid row">
                                <div class="col-md-6 p-2 grid-sizer"></div>
                                @foreach($nugget_images as $image)
                                    @php
                                        $url = $image->getUrl()
                                    @endphp
                                    <a class="grid-item col-md-6 p-2" href="{{url($url)}}" data-fancybox="grid-gallery" data-caption="{{$image->title}}">
                                        <div class="image-container">
                                            <div class="overlay"></div>
                                            <img class="shadow" src="{{url($url)}}">
                                            <i class="fa fa-camera icon"></i>
                                        </div>
                                    </a>
                                @endforeach
                            </div>
                            <div class="mt-4">
                                {{$nugget_images->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/site/nuggets.blade.php
@extends('layouts.site')
@section('content')
    <section>
     <div class="container p-0">
                    <div class="card no-bg glorious-blue basic-page">
                     <div class="card-header">
                         <h4 class="card-title text-uppercase mb-0">{{__($pageTitle ?? $naturalPageTitle)}}</h4>
                     </div>
                     <div class="card-body pb-0 pt-3 px-3">
                         <div class="row">
                             @foreach($nuggets as $nugget)
                                 <div class="col-md-6 mb-3 {{$loop->odd ? 'pr-md-0' : ''}}">
                                     <div class="card home-gallery-carousel-wrapper">
                                         <div class="card-header d-flex justify-content-between align-items-center">
                                             <h4 class="card-title text-uppercase mb-0">{{$nugget->title}}</h4>
                                             <small><a class="text-yellow mr-2" href="{{route('nuggets.show', $nugget)}}">{{__('See all')}}&nbsp;<i class="fa fa-angle-right"></i></a> </small>
                                         </div>
                                         <div class="card-body p-0">
                                             <div class="py-3">
                                                 @if($nugget->latest_images)
                                                     <div class="home-gallery-carousel owl-carousel owl-theme">
                                                         @foreach($nugget->latest_images as $image)
                                                             @php
                                                                 $url = $image->getUrl();
                                                             @endphp
                                                             <a class="item" href="{{url($url)}}" data-fancybox="grid-gallery" data-caption="{{$nugget->title}}">
                                                                 <div class="d-flex justify-content-center">
                                                                     <img style="max-height: 300px;" class="shadow" src="{{url($url)}}">
                                                                 </div>
                                                             </a>
                                                         @endforeach
                                                     </div>
                                                 @endif
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                             @endforeach
                             <div class="col-md-12">
                                 <div class="px-2">
                                     {{$nuggets->links()}}
                                 </div>
                             </div>
                         </div>
                     </div>


                 </div>
             </div>
    </section>
@endsection

resources/views/site/salvation-prayer.blade.php
@extends('layouts.site')
@section('content')
    <section>
     <div class="container p-0">
         <div class="row">
             <div class="col-md-12">
                 <div class="card basic-page">
                     <div class="card-header">
                         <h4 class="card-title text-uppercase mb-0">{{__($pageTitle)}}</h4>
                     </div>
                     <div class="card-body">
                         <div class="callout callout-theme">
                             <p class="highlight">{{__('site.salvation_prayer.body')}}</p>
                             <p class="text-yellow font-weight-bold">{{__('site.salvation_prayer.conclusion')}}</p>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
    </section>
@endsection

resources/views/site/sliders.blade.php
@extends('layouts.site')
@section('content')
    <section>
     <div class="container p-0">
         <div class="row">
             <div class="col-md-12">
                 <div class="card no-bg glorious-blue mb-4 basic-page">
                     <div class="card-header">
                         <h4 class="card-title text-uppercase mb-0">{{__($pageTitle ?? $naturalPageTitle)}}</h4>
                     </div>

                     <div class="card-body">
                         <div class="gallery-wrapper masonable-wrapper grid row no-gutters">
                             <div class="col-md-3 grid-sizer"></div>
                             @foreach($sliders as $image)
                                 <a class="grid-item col-md-3" href="{{url($image->image_url)}}" data-fancybox="grid-gallery" data-caption="{{$image->title}}">
                                     <div class="image-container">
                                         <div class="overlay"></div>
                                         <img class="shadow" src="{{url($image->image_url)}}">
                                         <i class="fa fa-camera icon"></i>
                                     </div>
                                 </a>
                             @endforeach
                         </div>
                         <div class="mt-4">
                             {{$sliders->links()}}
                         </div>
                     </div>
                     </div>
                 </div>
             </div>
         </div>
    </section>
@endsection

resources/views/site/statement-of-faith.blade.php
@extends('layouts.site')
@section('content')
    <section>
        <div class="container p-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="card basic-page">
                        <div class="card-header">
                            <h4 class="card-title text-uppercase mb-0">{{__($pageTitle)}}</h4>
                        </div>
                        <div class="card-body pb-3">
                            <div class="row">
                                @foreach($items as $item)
                                <div class="col-md-6 mb-4">
                                    <div class="callout callout-theme h-100">
                                        <h4 class="text-yellow">{{__('site.statement_of_faith.'.$item.'.title')}}</h4>
                                        <p>{{__('site.statement_of_faith.'.$item.'.body')}}</p>
                                    </div>
                                </div>
                                @endforeach
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection